### ISSUE TITLE
analyse create formation

### ISSUE THREAD

**Issue by EthanGoratel** [corentingoo/Learning_project_group_2#14]
- [ ] fonctionnelle
- [ ] technique
- [ ] stories

**Comment by francoisifo** [comment]
Fichiers MD:
[Analyse creation formation 14 _analyse fonct.md](https://github.com/corentingoo/Learning_project_group_2/files/9855006/Analyse.creation.formation.14._analyse.fonct.md)
[Analyse creation formation 14 _analyse tech.md](https://github.com/corentingoo/Learning_project_group_2/files/9855009/Analyse.creation.formation.14._analyse.tech.md)
[Analyse creation formation 14 _mockup.md](https://github.com/corentingoo/Learning_project_group_2/files/9855008/Analyse.creation.formation.14._mockup.md)
[Analyse creation formation 14 _modele de donnees.md](https://github.com/corentingoo/Learning_project_group_2/files/9855010/Analyse.creation.formation.14._modele.de.donnees.md)
[Analyse creation formation 14 _stories.md](https://github.com/corentingoo/Learning_project_group_2/files/9855007/Analyse.creation.formation.14._stories.md)


Fichiers images:

![Image](https://user-images.githubusercontent.com/90777424/197619188-40e7143b-6eb7-408e-9c71-2870835725f3.jpg)



![Image](https://user-images.githubusercontent.com/90777424/197619415-3ef567ae-e2a6-4ba2-bb93-23ba76f2870e.jpg)



![Image](https://user-images.githubusercontent.com/90777424/197619215-d7aa1ef2-1fb8-4755-8529-8edb4ba6a3fc.jpg)



![Image](https://user-images.githubusercontent.com/90777424/197619247-207aaf1d-a19e-4aaf-8c69-976e73d2e21d.jpg)




![Image](https://user-images.githubusercontent.com/90777424/197619666-f3334278-c535-49fb-831d-ea2a64cfbc21.jpg)



![Image](https://user-images.githubusercontent.com/90777424/197619778-a104e3ae-ada8-4060-9ad3-89244ed3f7db.jpg)


![Image](https://user-images.githubusercontent.com/90777424/197619511-2887dadb-95d8-4fb8-93e5-17b363bfb9a0.jpg)
